version: '3'
services:
  app:
    image: node
    environment:
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "cd react-material-ui-sample && yarn start"